name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  linting-and-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "requirements-dev.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"

      - name: Formatting and linters
        run: |
          flake8 logsight_cli tests setup.py --count --select=E9,F63,F7,F82 --show-source --statistics \
                 --exit-zero --max-complexity=10 --max-line-length=80
          pylint logsight_cli tests setup.py --disable=C0103,C0114,C0116,W0105,W0511,W0613,R0913,R0914,R0801,E1120,E1123,E1136

      - name: Build docs
        run: |
            echo "No docs to build yet"

  build:
    needs: linting-and-docs
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install test dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: 'Test with pytest (${{ runner.os }})'
        if: 'startsWith(runner.os, ''Linux'')'
        env:
          MIN_COVERAGE: 0
        run: |
          pytest tests -r a --cov=src --cov-report=xml
          if ! coverage report --fail-under=${MIN_COVERAGE} --show-missing
          then
              echo
              echo "Error: Test coverage has to be at least ${MIN_COVERAGE}"
              exit 0
          fi
      - name: 'Test with pytest (${{ runner.os }})'
        if: 'startsWith(runner.os, ''Windows'')'
        run: |
          pytest tests -r a

  test-install:
    needs: build
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python-version }}'
      - name: 'Install (${{ runner.os }})'
        if: >-
          startsWith(runner.os, 'Windows') && endsWith(matrix.python-version,'3.6')
        run: |
          pip install --upgrade --user pip wheel
      - name: 'Install (${{ runner.os }})'
        run: |
          pip install --upgrade pip wheel
          pip install .
      - name: Test installation
        run: |
          logsight --version

  publish:
    name: Publish to PyPI and TestPyPI
    needs: [test-install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: requirements.txt
          update-pip: 'false'
          update-setuptools: 'false'
          update-wheel: 'false'
      - name: Install build dependencies
        run: python -m pip install build wheel

      - name: Build binary wheel and a source distribution (to build distribution -bdist)
        run: python setup.py sdist

      - name: "Publish distribution \U0001F4E6 to Test PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: '${{ secrets.LOGSIGHT_CLI_TEST_PYPI_TOKEN }}'
          repository_url: 'https://test.pypi.org/legacy/'
      - name: "Publish distribution \U0001F4E6 to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: '${{ secrets.LOGSIGHT_CLI_PYPI_TOKEN }}'

  release:
    name: Release to GitHub
    needs: [test-install]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: latest_tag
        run: |
          echo "::set-output name=name::$(git tag --sort=-creatordate | head -1)"
          echo ${{ steps.latest_tag.name }}

      - name: Read CHANGELOG.rst
        id: changlog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOG.rst

      - name: Read CHANGELOG.rst file
        id: changelog
        run: echo "::set-output name=changelog::$(cat CHANGELOG.rst)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.latest_tag.name }}
          release_name: Release ${{ steps.latest_tag.name }}
          body: |
            ${{ steps.changlog.outputs.content }}
          draft: false
          prerelease: false